{
 "title": "Switch Data Statistics",
 "time": { "from": "2020-05-11T13:29:47.596Z", "to": "2020-05-11T15:02:22.591Z" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "query_result(sum by (instance)(ifInOctets{job=\"snmp\"}))"
   },
   {
    "name": "Interface",
    "query": "query_result(ifInOctets{job=\"snmp\",instance=\"$Device\"})"
   },
   { "name": "interval", "query": "5m,15m,30m,1h,3h,6h,12h,1d" },
   { "name": "LONG", "query": "6h,8h,12h,1d,4d,7d,15d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Uptime-$Device",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$Device\"}"
    }
   ]
  },
  {
   "title": "Percent packets in error ($interval) Inbound",
   "type": "bargauge",
   "description": "Percent of inbound packets that could not be transmitted during the most recent time interval because of error. (Threshold 2%)",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "((sum by (instance) (rate(ifInErrors{instance=\"$Device\"}[$interval]))) / ((sum by (instance) (rate(ifHCInUcastPkts{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifHCInBroadcastPkts{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifHCInMulticastPkts {instance=\"$Device\"}[$interval])))) * 100 )"
    }
   ]
  },
  {
   "title": "Percent packets in error ($interval) Inbound + Outbound",
   "type": "bargauge",
   "description": "Percent of total interface packets (both transmitted and received) that were in error during the most recent time interval. (Threshold 3%)",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "((sum by (instance) (rate(ifInErrors{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifOutErrors{instance=\"$Device\"}[$interval]))) / ((sum by (instance) (rate(ifHCInUcastPkts{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifHCInBroadcastPkts{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifHCInMulticastPkts {instance=\"$Device\"}[$interval])))+ (sum by (instance) (rate(ifHCOutUcastPkts{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifHCOutBroadcastPkts{instance=\"$Device\"}[$interval]))) + (sum by (instance) (rate(ifHCOutMulticastPkts {instance=\"$Device\"}[$interval])))) * 100 )"
    },
    {},
    {}
   ]
  },
  {
   "title": "Discards $Device ($interval)",
   "type": "graph",
   "description": "In and Out Discards by the instance in a day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "In vs Out Discards" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(ifInDiscards{instance='$Device'}[$interval]) )",
     "legendFormat": "In "
    },
    {
     "expr": "sum by (instance) (rate(ifOutDiscards{instance='$Device'}[$interval]) )",
     "legendFormat": "Out "
    }
   ]
  },
  {
   "title": "Errors $Device ($interval)",
   "type": "graph",
   "description": "In and Out errors by the instance in a day",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "In vs Out Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(ifInErrors{instance=\"$Device\"}[$interval]) ) ",
     "legendFormat": "In "
    },
    {
     "expr": "sum by (instance) (rate(ifOutErrors{instance=\"$Device\"}[$interval]))",
     "legendFormat": "Out "
    }
   ]
  },
  {
   "title": "Packets  for Broadcast and Multicast addresses for $Device ($LONG)",
   "type": "graph",
   "description": "Requested = Out  ; \nDelivered = In. This graph is the difference between packets requested vs packets transmitted",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    {
     "format": "bps",
     "label": "Requested (Out) / Delivered (In)"
    }
   ],
   "targets": [
    {
     "expr": "(sum by(instance) (rate(ifHCOutBroadcastPkts{instance=\"$Device\"}[$LONG])) or (sum by(instance) (rate(ifOutBroadcastPkts{instance=\"$Device\"}[$LONG])))) + (sum by (instance)  (rate(ifHCOutMulticastPkts{instance=\"$Device\"}[$LONG]))  or (sum by(instance) (rate(ifOutMulticastPkts{instance=\"$Device\"}[$LONG]))))",
     "legendFormat": "Requested "
    },
    {
     "expr": "(sum by(instance) (rate(ifHCInBroadcastPkts{instance=\"$Device\"}[$LONG])) or (sum by(instance) (rate(ifInBroadcastPkts{instance=\"$Device\"}[$LONG])))) + (sum by (instance)  (rate(ifHCInMulticastPkts{instance=\"$Device\"}[$LONG]))  or (sum by(instance) (rate(ifInMulticastPkts{instance=\"$Device\"}[$LONG]))))",
     "legendFormat": "Delivered"
    }
   ]
  },
  {
   "title": "Other Packets ($LONG)",
   "type": "graph",
   "description": "Requested = Out  ; \nDelivered = In. This graph is the difference between packets requested vs packets transmitted for Packets except broadcast and multicast",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    {
     "format": "bps",
     "label": "Requested (Out) - Delivered (In)"
    }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (rate(ifHCOutUcastPkts{instance=\"$Device\"}[$LONG]))) - (sum by (instance) (rate(ifHCInUcastPkts{instance=\"$Device\"}[$LONG])))",
     "legendFormat": "Requested - Delivered"
    },
    {}
   ]
  },
  {
   "title": "$Device Total In/Out [$interval]]",
   "type": "graph",
   "description": "The total number of octets received vs transmitted on the interface",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "Out Octets / In Octets" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(ifHCOutOctets{instance='$Device'}[$interval])) + sum by(instance)(irate(ifOutOctets{instance='$Device'}[$interval]))",
     "legendFormat": "Total Out"
    },
    {
     "expr": "- (sum by(instance)(irate(ifHCInOctets{instance='$Device'}[$interval])) + sum by(instance)(irate(ifInOctets{instance='$Device'}[$interval])))",
     "legendFormat": "Total In"
    }
   ]
  }
 ]
}